apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-analysis-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-analysis-service
  minReplicas: 1
  maxReplicas: 5  # 트래픽 증가 시 최대 5개까지 확장
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # CPU 사용률이 70%를 넘으면 파드 추가
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80 # 메모리 사용률이 80%를 넘으면 파드 추가